# Generated by Django 4.2.5 on 2024-01-08 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_sale_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0002_remove_orderitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirm', 'confirm'), ('deliverd', 'deliverd')], max_length=10)),
                ('categoty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
